# Fermipy example configuration
# for details see https://fermipy.readthedocs.io/en/latest/config.html
# for irfs, evtype and evclass options see https://fermi.gsfc.nasa.gov/ssc/data/analysis/documentation/Cicerone/Cicerone_Data/LAT_DP.html
components:
  - model: {isodiff: $GAMMAPY_DATA/fermi-gc/iso_P8R3_CLEAN_V3_PSF2_v1.txt}
    selection: {evtype: 16}  #4 is PSF0, 8 PSF1, 16 PSF2, 32 PSF3
    data: {ltcube: null}
  - model: {isodiff: $GAMMAPY_DATA/fermi-gc/iso_P8R3_CLEAN_V3_PSF3_v1.txt}
    selection: {evtype: 32}
    data: {ltcube: null}

data:
  evfile : ./raw/events_list.lst
  scfile : ./raw/L241227031840F357373F12_SC00.fits

binning:
  roiwidth   : 8.0
  binsz      : 0.1
  binsperdec   : 10
  coordsys : GAL
  proj: CAR
  projtype: WCS

selection :
#gtselect parameters
  emin : 3981.0717055349733 #ENERGY TRUE for gammapy
  emax : 2511886.4315095823 #ENERGY TRUE for gammapy
  zmax    : 105 # deg
  evclass : 256 #CLEAN
  tmin    : 239557417
  tmax    : 752112005

#gtmktime parameters
  filter : 'DATA_QUAL>0 && LAT_CONFIG==1'
  roicut : 'no'

#Set the ROI center to the coordinates of this source
  glon : 0.
  glat : 0.

fileio:
   outdir : ''
   logfile : 'out.log'
   usescratch : False
   scratchdir  : '/scratch'

gtlike:
  edisp : True
  edisp_bins : 0 # DO NOT CHANGE edisp_bins will be handled by gammapy
  irfs : 'P8R3_CLEAN_V3'

model:
  src_roiwidth : 10.0 #This is used by fermipy to compute the PSF RADMAX even if no models are set 