general:
    log: {level: info, filename: null, filemode: null, format: null, datefmt: null}
    outdir: .
observations:
    datastore: $GAMMAPY_DATA/hess-dl3-dr1/
    obs_ids: [20275]
datasets:
    type: 3d
    stack: true
    geom:
        wcs:
            skydir: {frame: icrs, lon: 187.3 deg, lat: 2.6 deg}
            binsize: 0.02 deg
            width: {width: 4.0 deg, height: 4.0 deg}
            binsize_irf: 0.5 deg
        selection: {offset_max: 2.5 deg}
        axes:
            energy: {min: 0.8 TeV, max: 10.0 TeV, nbins: 10}
            energy_true: {min: 0.4 TeV, max: 20.0 TeV, nbins: 20}
    on_region: {frame: icrs, lon: 187.3 deg, lat: 2.6 deg, radius: 0.11 deg}
    background:
        method: fov_background
        exclusion: null
        parameters: {}
    safe_mask:
        methods: [aeff-default, offset-max]
        parameters: {aeff_percent: 0.1, offset_max: 2.5 deg}
    containment_correction: true